name: Hello World

on:
  push:
    branches:
      - main
      - test
      - dev

jobs: 
  greet:
      runs-on: ubuntu-latest
      steps:
        - name: Muestra mensaje 'Hello World'
          run: echo "Hello World From GitHub with GitHub Actions"
