name: Trabajando con disparadores manuales

on:
  workflow_dispatch:
    inputs:
      text: 
        description: Label del campo
        required: true
      build:
        description: Tipo del Build
        type: choice
        default: release
        options: [debug, release]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Mostrando los valores de los inputs
        run: |
                echo "Label: ${{ inputs.text }}"
                echo "Build: ${{ inputs.build }}"
          
  
