name: Trabajando con multiples JOBS

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Imprime nombre del JOB (ubuntu)
        run: echo Job 1 (ubuntu)
  job-2:
    runs-on: macos-latest
    steps:
      - name: Imprime nombre JOB (macos)
        run: echo Job 2 (macos)
  job-3:
    runs-on: windows-latest
    steps: 
      - name: Imprime nombre de JOB (windows)
        run: echo Job 3 (windows)
    
