name: Pasando valores con outputs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Escribe una variable
        id: genera-valor
        run: echo "MI_VALOR='::crack::night::'" >> "$GITHUB_OUTPUT"

      - name: Obteniendo valor del paso anterior
        run: |
                echo "valor de variable: ${{ steps.genera-valor.outputs.MI_VALOR }}"
      - name: Enmascarando un valor
        id: enmascara
        run: |
                valor_secreto='::crack::night::'
                echo "::add-mask::$valor_secreto"
                echo "VALOR_SECRETO=$valor_secreto" >> "GITHUB_OUTPUT"
    
      - name: Obtener el valor secreto
        run: |
                 echo "Intentado imprimir valor secreto: ${{ steps.enmascara.outputs.VALOR_SECRETO }}"
