name: Triggers

on: 
  pull_request:
    branches: [main]
    paths:
      - 'code/**' # Se ejecutara el script si el pull request viene con cambios en la carpeta code
      - '.github/workflows/triggers.yml' #Si se modifica este archivo triggers.yml tambien se ejecutara el script.

jobs:

  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Saludo de bienvenida
        run: echo "Hello world from GitHub Actions"
        
  checkout_and_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Copia todos los archivos del repositorio al runer
        uses: actions/checkout@v4.2.2
        
      - name: Lista los archivos de mi repositorio
        run: |
                echo "El repositorio ${{github.repository}} contiene los siguientes archivos:"
                tree
