name: Trabajando con variables y secretos de GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo variables y secretos
        run: |
                echo "La variable es: ${{ vars.MI_VARIABLE }}"
                echo "El secreto es: ${{ secrets.CONNECTION_STRING }}"
      - name: Pasando Variables y Secretos a Variables de ambiente
        uses: actions/checkout@v4.2.2

      - name: Ejecutar codigo JS con nodeJS
        run: node main.js
        env:
          VARIABLE_CENTRALIZADA: ${{ vars.MI_VARIABLE }}
          SECRETO_CENTRALIZADO: ${{ secrets.CONNECTION_STRING }}
