name: Trabajando con variables y secretos de GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimiendo variables y secretos
        run: |
                echo "La variable es: ${{ vars.MI_VARIABLE }}"
                echo "El secreto es: ${{ secrets.CONNECTION_STRING }}"
