name: Trabajando con variables

on:
  workflow_dispatch:

env:
  variable_global: Valor de la variable global

jobs:
  job-1:
    runs-on: ubuntu-latest
    env: 
      varibale_job: Valor de variable de job
    steps:
      - name: step 1 job 1
        run: |
                echo "Imprimiendo valor de variable global -> ${{ env:variable_global }}"
                echo "Imprimiendo valor de variable de job -> ${{ env:variable_job }}"
                echo "Otra forma de obtener el valor de una variable -> $variable_global"
