name: Variables de Ambiente

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Nos traemos los archivos del actual repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurando variable de ambiente 
        run: echo "MI_VARIABLE='::crack::night::' " >> "$GITHUB_OUTPUT"

      - name: Ejecuta archivo de Javascript con NodeJS
        run: node main.js
      
